# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U tox
    - curl -L https://github.com/coreos/etcd/releases/download/v3.0.10/etcd-v3.0.10-linux-amd64.tar.gz -o etcd-v3.0.10-linux-amd64.tar.gz
    - tar xzvf etcd-v3.0.10-linux-amd64.tar.gz
    - export PATH=$PATH:etcd-v3.0.10-linux-amd64
    - etcd &

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kragniz
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: kragniz/python-etcd3
    condition: $TOXENV == py27
